-- Database: INFOPLUS
-- DROP DATABASE "INFOPLUS";

CREATE DATABASE "INFOPLUS" WITH OWNER = "ENTREPRISE" ENCODING = 'UTF8' LC_COLLATE = 'French_France.1252' LC_CTYPE = 'French_France.1252' TABLESPACE = pg_default CONNECTION
LIMIT = -1;