/*------------------------ INFOPLUS----------------------------------------*/
/*Script de DROP des tables si elles existent DROP TABLE IF EXISTS CLIENT;*/
DROP TABLE IF EXISTS SALARIE_EQUIPE;
DROP TABLE IF EXISTS SALARIE_FONCTION;
DROP TABLE IF EXISTS SALARIE_TACHE;
DROP TABLE IF EXISTS MATERIEL_COMPOSE;
DROP TABLE IF EXISTS MATERIEL;
DROP TABLE IF EXISTS SALARIE;
DROP TABLE IF EXISTS DIVISION;
DROP TABLE IF EXISTS LOCALITES;
DROP TABLE IF EXISTS CONTACT;
DROP TABLE IF EXISTS TACHE;
DROP TABLE IF EXISTS PROJET;
DROP TABLE IF EXISTS CLIENT;
DROP TABLE IF EXISTS EQUIPE;
DROP TABLE IF EXISTS POLE_COMPETENCE;
DROP TABLE IF EXISTS FONCTION;


